export const BASE_METADATA = {
  title: 'Onikuma',
  siteName: 'Onikuma | On-Chain Social Game',
  description: 'Redefining Gaming on Berachain.',
  keywords: [
    'Onikuma',
    'Crypto',
    'Onchain',
    'Blockchain',
    'Social',
    'Game',
    'Berachain',
    'Strategize',
    'Influence',
    'Dominate',
    'Bet',
  ],
  url: 'https://onikuma.world',
  image: 'https://dev-onikuma-s3.s3.ap-northeast-2.amazonaws.com/Hero.png',
  ogImage: '/metadata/og-image.png',
};
