export const MUTATION_KEY = {
  POST_COMMENTS: 'POST_COMMENTS',
  POST_LIKES: 'POST_LIKES',
  POST_POOL_IN: 'POST_POOL_IN',
  POST_VOTE: 'POST_VOTE',
  POST_LOGIN: 'POST_LOGIN',
  POST_UPLOAD_IMAGE: 'POST_UPLOAD_IMAGE',
  POST_IMAGE: 'POST_IMAGE',
  POST_VOICE: 'POST_VOICE',
  CONFIRM_VOICE: 'CONFIRM_VOICE',
} as const;
