export const QUERY_KEY = {
  GET_COMMENTS: 'GET_COMMENTS',
  GET_LIKES: 'GET_LIKES',
  GET_SHARE_IMAGE: 'GET_SHARE_IMAGE',
  GET_RESULT_IMAGE: 'GET_RESULT_IMAGE',
  GET_RECENT_ACTIVITIES: 'GET_RECENT_ACTIVITIES',
  GET_POLL_RESULT: 'GET_POLL_RESULT',
  GET_TOPIC_TITLE: 'GET_TOPIC_TITLE',
  GET_ALL_RANKINGS: 'GET_ALL_RANKINGS',
} as const;
